### ISSUE TITLE
Update model with html, ajax and js implementation

### ISSUE THREAD

**Issue by MSSoumya** [vlead/analytics#13]
Currently the model has the code which requests the service to display the page views. This needs to be updated with the service which displays the usage.

**Comment by madhavipuliraju** [comment]
The service was implemented to display the usage with some dummy value (because usage script is not yet ready) and tested on http://stats-demo.vlabs.ac.in/test-stats/ (test environment). It also need to test on http://stats-demo.vlabs.ac.in/stats/ (production). But, It was dependent on issue #8.
