### ISSUE TITLE
[Analytics] A display page to show the usages

### ISSUE THREAD

**Issue by MSSoumya** [vlead/analytics#7]
A basic page which would display the usage needs to be created.

**Comment by madhavipuliraju** [comment]
Embeded Ajax and javascript code to display the usage. Currently, this code was updated on http://stats-demo.vlabs.ac.in/test-stats/ (test environment) showing some dummy value. Also, need to update on http://stats-demo.virtual-labs.ac.in/stats/ (production) . But, It was dependent on issue #8.
